// Code generated by MockGen. DO NOT EDIT.
// Source: internal/blog/post/application/commands/createOne/command.go
//
// Generated by this command:
//
//	mockgen -source=internal/blog/post/application/commands/createOne/command.go -destination=internal/blog/post/application/mocks/create_one_post_mock.go -package=mocks -mock_names=Handler=MockCreateOnePostHandler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	createOne "github.com/CXTACLYSM/hiring-api/internal/blog/post/application/commands/createOne"
	entities "github.com/CXTACLYSM/hiring-api/internal/blog/post/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateOnePostHandler is a mock of Handler interface.
type MockCreateOnePostHandler struct {
	ctrl     *gomock.Controller
	recorder *MockCreateOnePostHandlerMockRecorder
	isgomock struct{}
}

// MockCreateOnePostHandlerMockRecorder is the mock recorder for MockCreateOnePostHandler.
type MockCreateOnePostHandlerMockRecorder struct {
	mock *MockCreateOnePostHandler
}

// NewMockCreateOnePostHandler creates a new mock instance.
func NewMockCreateOnePostHandler(ctrl *gomock.Controller) *MockCreateOnePostHandler {
	mock := &MockCreateOnePostHandler{ctrl: ctrl}
	mock.recorder = &MockCreateOnePostHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateOnePostHandler) EXPECT() *MockCreateOnePostHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockCreateOnePostHandler) Handle(arg0 createOne.Command) (*entities.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", arg0)
	ret0, _ := ret[0].(*entities.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockCreateOnePostHandlerMockRecorder) Handle(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockCreateOnePostHandler)(nil).Handle), arg0)
}
