// Code generated by MockGen. DO NOT EDIT.
// Source: internal/blog/post/application/commands/deleteOne/command.go
//
// Generated by this command:
//
//	mockgen -source=internal/blog/post/application/commands/deleteOne/command.go -destination=internal/blog/post/application/mocks/delete_one_post_mock.go -package=mocks -mock_names=Handler=MockDeleteOnePostHandler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	deleteOne "github.com/CXTACLYSM/hiring-api/internal/blog/post/application/commands/deleteOne"
	gomock "go.uber.org/mock/gomock"
)

// MockDeleteOnePostHandler is a mock of Handler interface.
type MockDeleteOnePostHandler struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteOnePostHandlerMockRecorder
	isgomock struct{}
}

// MockDeleteOnePostHandlerMockRecorder is the mock recorder for MockDeleteOnePostHandler.
type MockDeleteOnePostHandlerMockRecorder struct {
	mock *MockDeleteOnePostHandler
}

// NewMockDeleteOnePostHandler creates a new mock instance.
func NewMockDeleteOnePostHandler(ctrl *gomock.Controller) *MockDeleteOnePostHandler {
	mock := &MockDeleteOnePostHandler{ctrl: ctrl}
	mock.recorder = &MockDeleteOnePostHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleteOnePostHandler) EXPECT() *MockDeleteOnePostHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockDeleteOnePostHandler) Handle(arg0 deleteOne.Command) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockDeleteOnePostHandlerMockRecorder) Handle(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockDeleteOnePostHandler)(nil).Handle), arg0)
}
