// Code generated by MockGen. DO NOT EDIT.
// Source: internal/blog/post/application/queries/findOne/query.go
//
// Generated by this command:
//
//	mockgen -source=internal/blog/post/application/queries/findOne/query.go -destination=internal/blog/post/application/mocks/find_one_post_mock.go -package=mocks -mock_names=Handler=MockFindOnePostHandler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	findOne "github.com/CXTACLYSM/hiring-api/internal/blog/post/application/queries/findOne"
	entities "github.com/CXTACLYSM/hiring-api/internal/blog/post/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockFindOnePostHandler is a mock of Handler interface.
type MockFindOnePostHandler struct {
	ctrl     *gomock.Controller
	recorder *MockFindOnePostHandlerMockRecorder
	isgomock struct{}
}

// MockFindOnePostHandlerMockRecorder is the mock recorder for MockFindOnePostHandler.
type MockFindOnePostHandlerMockRecorder struct {
	mock *MockFindOnePostHandler
}

// NewMockFindOnePostHandler creates a new mock instance.
func NewMockFindOnePostHandler(ctrl *gomock.Controller) *MockFindOnePostHandler {
	mock := &MockFindOnePostHandler{ctrl: ctrl}
	mock.recorder = &MockFindOnePostHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFindOnePostHandler) EXPECT() *MockFindOnePostHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockFindOnePostHandler) Handle(arg0 findOne.Query) (*entities.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", arg0)
	ret0, _ := ret[0].(*entities.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockFindOnePostHandlerMockRecorder) Handle(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockFindOnePostHandler)(nil).Handle), arg0)
}
