// Code generated by MockGen. DO NOT EDIT.
// Source: internal/blog/post/application/queries/findList/query.go
//
// Generated by this command:
//
//	mockgen -source=internal/blog/post/application/queries/findList/query.go -destination=internal/blog/post/application/mocks/find_list_post_mock.go -package=mocks -mock_names=Handler=MockFindListPostHandler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	findList "github.com/CXTACLYSM/hiring-api/internal/blog/post/application/queries/findList"
	entities "github.com/CXTACLYSM/hiring-api/internal/blog/post/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockFindListPostHandler is a mock of Handler interface.
type MockFindListPostHandler struct {
	ctrl     *gomock.Controller
	recorder *MockFindListPostHandlerMockRecorder
	isgomock struct{}
}

// MockFindListPostHandlerMockRecorder is the mock recorder for MockFindListPostHandler.
type MockFindListPostHandlerMockRecorder struct {
	mock *MockFindListPostHandler
}

// NewMockFindListPostHandler creates a new mock instance.
func NewMockFindListPostHandler(ctrl *gomock.Controller) *MockFindListPostHandler {
	mock := &MockFindListPostHandler{ctrl: ctrl}
	mock.recorder = &MockFindListPostHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFindListPostHandler) EXPECT() *MockFindListPostHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockFindListPostHandler) Handle(arg0 findList.Query) ([]*entities.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", arg0)
	ret0, _ := ret[0].([]*entities.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockFindListPostHandlerMockRecorder) Handle(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockFindListPostHandler)(nil).Handle), arg0)
}
