// Code generated by MockGen. DO NOT EDIT.
// Source: internal/blog/post/application/commands/updateOne/command.go
//
// Generated by this command:
//
//	mockgen -source=internal/blog/post/application/commands/updateOne/command.go -destination=internal/blog/post/application/mocks/update_one_post_mock.go -package=mocks -mock_names=Handler=MockUpdateOnePostHandler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	updateOne "github.com/CXTACLYSM/hiring-api/internal/blog/post/application/commands/updateOne"
	entities "github.com/CXTACLYSM/hiring-api/internal/blog/post/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockUpdateOnePostHandler is a mock of Handler interface.
type MockUpdateOnePostHandler struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateOnePostHandlerMockRecorder
	isgomock struct{}
}

// MockUpdateOnePostHandlerMockRecorder is the mock recorder for MockUpdateOnePostHandler.
type MockUpdateOnePostHandlerMockRecorder struct {
	mock *MockUpdateOnePostHandler
}

// NewMockUpdateOnePostHandler creates a new mock instance.
func NewMockUpdateOnePostHandler(ctrl *gomock.Controller) *MockUpdateOnePostHandler {
	mock := &MockUpdateOnePostHandler{ctrl: ctrl}
	mock.recorder = &MockUpdateOnePostHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateOnePostHandler) EXPECT() *MockUpdateOnePostHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockUpdateOnePostHandler) Handle(arg0 updateOne.Command) (*entities.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", arg0)
	ret0, _ := ret[0].(*entities.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockUpdateOnePostHandlerMockRecorder) Handle(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockUpdateOnePostHandler)(nil).Handle), arg0)
}
