// Code generated by MockGen. DO NOT EDIT.
// Source: internal/auth/user/application/commands/createOne/command.go
//
// Generated by this command:
//
//	mockgen -source=internal/auth/user/application/commands/createOne/command.go -destination=internal/auth/user/application/mocks/create_one_user_mock.go -package=mocks -mock_names=Handler=MockCreateOneUserHandler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	createOne "github.com/CXTACLYSM/hiring-api/internal/auth/user/application/commands/createOne"
	entities "github.com/CXTACLYSM/hiring-api/internal/auth/user/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockCreateOneUserHandler is a mock of Handler interface.
type MockCreateOneUserHandler struct {
	ctrl     *gomock.Controller
	recorder *MockCreateOneUserHandlerMockRecorder
	isgomock struct{}
}

// MockCreateOneUserHandlerMockRecorder is the mock recorder for MockCreateOneUserHandler.
type MockCreateOneUserHandlerMockRecorder struct {
	mock *MockCreateOneUserHandler
}

// NewMockCreateOneUserHandler creates a new mock instance.
func NewMockCreateOneUserHandler(ctrl *gomock.Controller) *MockCreateOneUserHandler {
	mock := &MockCreateOneUserHandler{ctrl: ctrl}
	mock.recorder = &MockCreateOneUserHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateOneUserHandler) EXPECT() *MockCreateOneUserHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockCreateOneUserHandler) Handle(arg0 createOne.Command) (*entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", arg0)
	ret0, _ := ret[0].(*entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockCreateOneUserHandlerMockRecorder) Handle(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockCreateOneUserHandler)(nil).Handle), arg0)
}
