// Code generated by MockGen. DO NOT EDIT.
// Source: internal/auth/user/application/queries/findOne/query.go
//
// Generated by this command:
//
//	mockgen -source=internal/auth/user/application/queries/findOne/query.go -destination=internal/auth/user/application/mocks/find_one_user_mock.go -package=mocks -mock_names=Handler=MockFindOneUserHandler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	findOne "github.com/CXTACLYSM/hiring-api/internal/auth/user/application/queries/findOne"
	entities "github.com/CXTACLYSM/hiring-api/internal/auth/user/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockFindOneUserHandler is a mock of Handler interface.
type MockFindOneUserHandler struct {
	ctrl     *gomock.Controller
	recorder *MockFindOneUserHandlerMockRecorder
	isgomock struct{}
}

// MockFindOneUserHandlerMockRecorder is the mock recorder for MockFindOneUserHandler.
type MockFindOneUserHandlerMockRecorder struct {
	mock *MockFindOneUserHandler
}

// NewMockFindOneUserHandler creates a new mock instance.
func NewMockFindOneUserHandler(ctrl *gomock.Controller) *MockFindOneUserHandler {
	mock := &MockFindOneUserHandler{ctrl: ctrl}
	mock.recorder = &MockFindOneUserHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFindOneUserHandler) EXPECT() *MockFindOneUserHandlerMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockFindOneUserHandler) Handle(arg0 findOne.Query) (*entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", arg0)
	ret0, _ := ret[0].(*entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockFindOneUserHandlerMockRecorder) Handle(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockFindOneUserHandler)(nil).Handle), arg0)
}
